pipeline {
    agent any
    
    environment {
        // Пути для Windows
        PATH = "C:\\Users\\safry\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe;C:\\Python 3.9\\Scripts\\pip.exe"
		PYTHON_VENV = "${WORKSPACE}\\lab2\\venv"
        DATA_DIR = "${WORKSPACE}\\lab2\\artifacts\\data"
        MODEL_DIR = "${WORKSPACE}\\lab2\\artifacts\\models"
        REPORT_DIR = "${WORKSPACE}\\lab2\\artifacts\\reports"
        VENV_ACTIVATE = "${WORKSPACE}\\lab2\\venv\\Scripts\\activate.bat"
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                echo "✅ Code received from repo"
            }
        }
        
        stage('Setup Python') {
            steps {
                powershell '''
					Set-Location "${env:WORKSPACE}\\lab2"
					python -m venv venv
					& .\\venv\\Scripts\\Activate.ps1
					python -m pip install --upgrade pip
					pip install -r requirements.txt
				'''
            }
        }
        
        stage('Data Creation') {
            steps {
                powershell '''
					& "${env:WORKSPACE}\\lab2\\venv\\Scripts\\Activate.ps1"
					Set-Location "${env:WORKSPACE}\\lab2"
                    python data_creation.py --output-dir artifacts\\data --source synthetic
                '''
            }
        }
        
        stage('Data Preprocessing') {
            steps {
                powershell '''
					& "${env:WORKSPACE}\\lab2\\venv\\Scripts\\Activate.ps1"
					Set-Location "${env:WORKSPACE}\\lab2"
                    python data_preprocessing.py --data-dir artifacts\\data --output-dir artifacts\\data
                '''
            }
        }
        
        stage('Model Training') {
            steps {
                powershell '''
					& "${env:WORKSPACE}\\lab2\\venv\\Scripts\\Activate.ps1"
					Set-Location "${env:WORKSPACE}\\lab2"
                    python model_preparation.py --data-dir artifacts\\data --model-dir artifacts\\models
                '''
            }
        }
        
        stage('Model Testing') {
            steps {
                powershell '''
					& "${env:WORKSPACE}\\lab2\\venv\\Scripts\\Activate.ps1"
					Set-Location "${env:WORKSPACE}\\lab2"
                    python model_testing.py --data-dir artifacts\\data --model-dir artifacts\\models --report-dir artifacts\\reports
                '''
            }
        }
    }
    
    post {
        always {
            cleanWs(
                cleanWhenAborted: false,
                notFailBuild: true,
                deleteDirs: true,
                disableDeferredWipeout: false
            )
            echo "🧹 Workspace cleaned"
        }
        failure {
            echo "❌ Pipeline failed. Check Console Output."
        }
        success {
            echo "🎉 Pipeline completed successfully!"
        }
    }
}